Add examples
eclipse-uprotocol/up-zenoh-example-rust pull request #1
Opened 2024-03-08 06:27 UTC by evshary

Move the examples from up-client-zenoh-rust to this repository.

2024-03-11 11:58 UTC, stevenhartley requested changes
Please add missing legal info (LICENSE, CONTRIBUTING.adoc) and add the workflows to build, test, lint from up-rust

2024-03-12 07:44 UTC, evshary commented
Done. I found that I also missed adding LICENSE and CONTRIBUTING in up-client-zenoh-rust.

2024-03-19 09:19 UTC, evshary commented
@stevenhartley maybe we can merge the initial examples if you don't have other comments.

2024-03-19 15:21 UTC, stevenhartley approved these changes

2024-03-19 15:21 UTC, merged